#!/usr/bin/env node
/**
 * Self-hosts the four Google fonts the design uses.
 *
 * Asking Google for the CSS with a modern browser's user agent gets back
 * woff2 files already subset per script, which is why this fetches from
 * them rather than shipping the full families. The files land in
 * public/fonts/ and the rewritten @font-face rules in src/styles/fonts.css.
 *
 * Run:  node scripts/fonts.mjs
 */
import { writeFileSync, mkdirSync, readdirSync, rmSync } from "node:fs";
import { createHash } from "node:crypto";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT_DIR = join(ROOT, "public/fonts");
const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36";

const CSS_URL =
  "https://fonts.googleapis.com/css2?family=Caveat:wght@500;700" +
  "&family=Courier+Prime:ital,wght@0,400;0,700;1,400" +
  "&family=Fraunces:ital,opsz,wght@0,9..144,400;0,9..144,600;1,9..144,400;1,9..144,600" +
  "&family=Noto+Serif+Devanagari:wght@400;600&display=swap";

/** The scripts this blog actually sets: English prose and Hindi verse. */
const KEEP = new Set(["latin", "latin-ext", "devanagari"]);

rmSync(OUT_DIR, { recursive: true, force: true });
mkdirSync(OUT_DIR, { recursive: true });

const css = await (await fetch(CSS_URL, { headers: { "User-Agent": UA } })).text();

/* Google emits a `/* subset *\/` comment before each @font-face. */
const blocks = css
  .split("/*")
  .slice(1)
  .map((chunk) => {
    const subset = chunk.slice(0, chunk.indexOf("*/")).trim();
    const rule = chunk.slice(chunk.indexOf("*/") + 2).trim();
    return { subset, rule };
  })
  .filter((b) => b.rule.startsWith("@font-face") && KEEP.has(b.subset));

if (!blocks.length) throw new Error("Google returned no usable @font-face blocks.");

const field = (rule, name) => (rule.match(new RegExp(`${name}:\\s*([^;]+);`)) ?? [])[1]?.trim();

const out = [];
/* Google serves one variable file for several weights, so the same bytes
   arrive under several URLs. Naming files by content hash means the browser
   downloads each one once. */
const seen = new Map();

for (const { subset, rule } of blocks) {
  const url = rule.match(/url\((https:[^)]+)\)/)?.[1];
  if (!url) continue;

  const family = field(rule, "font-family").replace(/['"]/g, "");
  const weight = field(rule, "font-weight");
  const style = field(rule, "font-style");
  const range = field(rule, "unicode-range");

  const res = await fetch(url, { headers: { "User-Agent": UA } });
  if (!res.ok) throw new Error(`${family} ${style} ${weight} ${subset}: ${res.status}`);
  const bytes = Buffer.from(await res.arrayBuffer());
  const hash = createHash("sha256").update(bytes).digest("hex").slice(0, 8);

  const stem = `${family.replace(/\s+/g, "")}-${subset}`.toLowerCase();
  const file = seen.get(hash) ?? `${stem}-${hash}.woff2`;
  if (!seen.has(hash)) {
    writeFileSync(join(OUT_DIR, file), bytes);
    seen.set(hash, file);
  }

  out.push(
    `/* ${subset} */\n@font-face {\n` +
      `  font-family: "${family}";\n` +
      `  font-style: ${style};\n` +
      `  font-weight: ${weight};\n` +
      `  font-display: swap;\n` +
      `  src: url("/blog/fonts/${file}") format("woff2");\n` +
      (range ? `  unicode-range: ${range};\n` : "") +
      `}`,
  );
}

writeFileSync(
  join(ROOT, "src/styles/fonts.css"),
  "/* Generated by scripts/fonts.mjs. Do not edit by hand. */\n\n" + out.join("\n\n") + "\n",
);

console.log(`${out.length} @font-face rules over ${seen.size} distinct file(s) -> public/fonts/`);
